version: '3.7'
services:
    backApi_container:
        image: back:latest
        restart: always
        expose:
            -3000
    mongodb_container:
        image: mongo:latest
        restart: always
        environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootpassword
        ports:
        - 27017:27017
        volumes:
        - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: