version: '3.7'

services:
    backApi_container:
        image: tytoback:latest
        build:
            context: "./backend"
            dockerfile: ./DockerFile
      
        restart: always
        expose:
            - "4000"
        env_file:
            - ./.env
        networks:
            - webnet
    front_container:
        image: tytofront:latest
        build:
            context: "./frontend"
            dockerfile: ./Dockerfile
        
        restart: always
        expose:
            - "3000"
        networks:
            - webnet      
    mongodb_container:
        image: mongo:latest
        restart: always
        env_file:
            - ./.env
        ports:
        - 27017:27017
        volumes:
        - mongodb_data_container:/data/db
        networks:
            - webnet
    nginx_server:
        image: "nginx:alpine"
        container_name: "nginx"
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
        links:
            - mongodb_container
        networks:
            - webnet
        ports:
            - "80:80"
            - "443:443"
            
volumes:
  mongodb_data_container:

networks:
    webnet:
        driver: bridge
      