name: Node CI

on: [push]

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: install node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: backend
        working-directory: ./backend
        run: |
          docker login docker.pkg.github.com --username straxico --password ${{ secrets.DOCKER_PASSWORD }}
          docker build . --file DockerFile --tag docker.pkg.github.com/straxico/tyto/backend:latest
          docker push docker.pkg.github.com/straxico/tyto/backend:latest
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: frontend
        working-directory: ./frontend
        run: |
          docker login docker.pkg.github.com --username straxico --password ${{ secrets.DOCKER_PASSWORD }}
          docker build . --file Dockerfile --tag docker.pkg.github.com/straxico/tyto/frontend:latest
          docker push docker.pkg.github.com/straxico/tyto/frontend:latest
